variable "project" {}
variable "env" {}
variable "app_name" {}
variable "repository" {}
variable "codepipeline_bucket" {}
variable "ecr_repository_url" {}
variable "source_version" {}
variable "current_id" {}
variable "ecs_task_role" {}
variable "ecs_task_execution_role" {}
variable "ecs_task_log_group" {}
variable "task_definition" {}
variable "container_port" {}
variable "codestarconnections_arn" {}
variable "codedeploy_app" {}
variable "codedeploy_deployment_group" {}
